version: '3.0'

services:
  frontend:
    container_name: app-frontend
    image: nginx-frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    volumes:
      - ./nginx-logs:/var/log/nginx
    ports:
      - "80:80"
      - "8090:8090"
    networks:
      - frontend
      - backend

  backend:
    container_name: app-backend
    image: nginx-backend
    build:
      context: ./backend
    networks:
      - backend

networks:
  frontend:
  backend:
