version: '3.0'

services:
  frontend:
    container_name: app-frontend
    image: nginx-frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    volumes:
      - ./nginx-logs:/var/log/nginx

  backend:
    container_name: app-backend
    image: nginx-backend
    build:
      context: ./backend

networks:
  default:
    external:
      name: server-private
